//! Nushell completion script renderer.
//!
//! References:
//! - https://www.nushell.sh/book/custom_completions.html
//! - https://www.nushell.sh/book/externs.html

const std = @import("std");

const Command = @import("../Command.zig");

pub fn render(writer: *std.Io.Writer, root: *const Command, path: []const u8, is_root: bool) !void {
    if (is_root) {
        try renderHeader(writer, root);
        try writer.print("module completions {{\n\n", .{});
        try renderCompleters(writer, root);
        try renderValueCompleters(writer, root, path);
    }

    try renderExternHeader(writer, path, is_root);
    try renderFlags(writer, root, path);
    try renderPositionals(writer, root, path);
    try writer.print("  ]\n\n", .{});

    for (root.subcommands.items) |sub| {
        const child_path = try std.fmt.allocPrint(std.heap.page_allocator, "{s} {s}", .{ path, sub.name });
        defer std.heap.page_allocator.free(child_path);
        try render(writer, sub, child_path, false);
    }

    if (is_root) {
        try writer.print("}}\n\nexport use completions *\n", .{});
    }
}

fn renderHeader(writer: *std.Io.Writer, root: *const Command) !void {
    const display_name = if (root.display_name.len > 0) root.display_name else root.name;
    try writer.print(
        \\# Generated by Fangz for {s}.
        \\#
        \\# Source this file from Nushell with:
        \\#
        \\#   source {s}.nu
        \\#
        \\# Or place it somewhere stable and source it from your Nushell config.
        \\
        \\
    , .{ display_name, root.name });
}

fn renderCompleters(writer: *std.Io.Writer, root: *const Command) !void {
    var completers: std.ArrayList(Command.NuCompleter) = .empty;
    defer completers.deinit(std.heap.page_allocator);

    try collectCompleters(root, &completers);
    for (completers.items) |completer| {
        try writer.print("  def {s} [{s}] {{\n", .{ completer.name, completer.params });
        try renderIndentedBody(writer, completer.body);
        try writer.print("  }}\n\n", .{});
    }
}

fn renderIndentedBody(writer: *std.Io.Writer, body: []const u8) !void {
    var rest = body;
    while (rest.len > 0) {
        const newline = std.mem.indexOfScalar(u8, rest, '\n') orelse rest.len;
        try writer.print("    {s}\n", .{rest[0..newline]});
        rest = if (newline < rest.len) rest[newline + 1 ..] else "";
    }
}

fn renderValueCompleters(writer: *std.Io.Writer, root: *const Command, path: []const u8) !void {
    for (root.flags.constSlice()) |flag| {
        try renderFlagCompleter(writer, path, flag);
    }

    for (root.positionals.items) |pos| {
        try renderPositionalCompleter(writer, path, pos);
    }

    for (root.subcommands.items) |sub| {
        const child_path = try std.fmt.allocPrint(std.heap.page_allocator, "{s} {s}", .{ path, sub.name });
        defer std.heap.page_allocator.free(child_path);
        try renderValueCompleters(writer, sub, child_path);
    }
}

fn renderFlagCompleter(writer: *std.Io.Writer, path: []const u8, flag: Command.Flag) !void {
    if (!hasFlagValueCompleter(flag)) return;

    const name = try flagCompleterName(path, flag.name);
    defer std.heap.page_allocator.free(name);

    try writer.print("  def {s} [] {{\n    [\n", .{name});
    if (flag.value_type == .key_value_list) {
        // Prefer `key=` suggestions so the shell can complete the level after `=` (see dynamic `__complete` too).
        if (flag.key_value_help) |kv| {
            for (kv.keys) |meta| try writer.print("      \"{s}=\"\n", .{meta.name});
        } else if (flag.allowed_keys) |keys| {
            for (keys) |key| try writer.print("      \"{s}=\"\n", .{key});
        } else if (flag.allowed_values) |values| {
            for (values) |value| try writer.print("      \"{s}\"\n", .{value});
        }
    } else if (flag.allowed_values) |values| {
        for (values) |value| try writer.print("      \"{s}\"\n", .{value});
    }
    try writer.print("    ]\n  }}\n\n", .{});
}

fn hasFlagValueCompleter(flag: Command.Flag) bool {
    if (flag.value_type == .key_value_list) {
        return flag.key_value_help != null or flag.allowed_keys != null or flag.allowed_values != null;
    }

    return flag.allowed_values != null and flag.allowed_values.?.len > 0;
}

fn renderPositionalCompleter(writer: *std.Io.Writer, path: []const u8, pos: Command.Positional) !void {
    const values = pos.allowed_values orelse return;
    if (values.len == 0) return;

    const name = try positionalCompleterName(path, pos.name);
    defer std.heap.page_allocator.free(name);

    try writer.print("  def {s} [] {{\n    [\n", .{name});
    for (values) |value| try writer.print("      \"{s}\"\n", .{value});
    if (std.mem.eql(u8, pos.name, "shell") and containsValue(values, "nu") and !containsValue(values, "nushell")) {
        try writer.print("      \"nushell\"\n", .{});
    }
    try writer.print("    ]\n  }}\n\n", .{});
}

fn collectCompleters(cmd: *const Command, out: *std.ArrayList(Command.NuCompleter)) !void {
    for (cmd.positionals.items) |pos| {
        const completer = pos.completion.nu orelse continue;
        if (!containsCompleter(out.items, completer.name)) {
            try out.append(std.heap.page_allocator, completer);
        }
    }

    for (cmd.subcommands.items) |sub| {
        try collectCompleters(sub, out);
    }
}

fn containsCompleter(items: []const Command.NuCompleter, name: []const u8) bool {
    for (items) |existing| {
        if (std.mem.eql(u8, existing.name, name)) return true;
    }
    return false;
}

fn renderExternHeader(writer: *std.Io.Writer, path: []const u8, is_root: bool) !void {
    if (is_root) {
        try writer.print("  export extern {s} [\n", .{path});
    } else {
        try writer.print("  export extern \"{s}\" [\n", .{path});
    }
}

fn renderFlags(writer: *std.Io.Writer, root: *const Command, path: []const u8) !void {
    for (root.flags.constSlice()) |flag| {
        try renderFlag(writer, path, flag);
    }

    try writer.print("    --help(-h) # Print help\n", .{});
    if (root.parent == null and root.rootConst().version != null) {
        try writer.print("    --version(-V) # Print version\n", .{});
    }
}

fn renderFlag(writer: *std.Io.Writer, path: []const u8, flag: Command.Flag) !void {
    const completer = if (hasFlagValueCompleter(flag)) try flagCompleterAnnotation(path, flag.name) else "";
    defer if (completer.len > 0) std.heap.page_allocator.free(completer);

    if (flag.short) |short| {
        if (flag.takesValue()) {
            try writer.print("    --{s}(-{c}): string{s}", .{ flag.name, short, completer });
        } else {
            try writer.print("    --{s}(-{c})", .{ flag.name, short });
        }
        try renderHelpComment(writer, flag.description);
        return;
    }

    if (flag.takesValue()) {
        try writer.print("    --{s}: string{s}", .{ flag.name, completer });
    } else {
        try writer.print("    --{s}", .{flag.name});
    }
    try renderHelpComment(writer, flag.description);
}

fn renderPositionals(writer: *std.Io.Writer, root: *const Command, path: []const u8) !void {
    if (root.positionals.items.len > 0) try writer.print("\n", .{});

    for (root.positionals.items) |pos| {
        const at_completer = try positionalCompleterAnnotation(path, pos);
        defer if (at_completer.len > 0) std.heap.page_allocator.free(at_completer);

        const nu_name = try std.mem.replaceOwned(u8, std.heap.page_allocator, pos.name, "-", "_");
        defer std.heap.page_allocator.free(nu_name);

        if (pos.variadic) {
            try writer.print("    ...{s}: string{s}", .{ nu_name, at_completer });
        } else if (pos.required) {
            try writer.print("    {s}: string{s}", .{ nu_name, at_completer });
        } else {
            try writer.print("    {s}?: string{s}", .{ nu_name, at_completer });
        }
        try renderHelpComment(writer, pos.description);
    }
}

fn renderHelpComment(writer: *std.Io.Writer, description: []const u8) !void {
    const merged = try mergeHelpCommentWords(std.heap.page_allocator, description);
    defer std.heap.page_allocator.free(merged);

    if (merged.len == 0) {
        try writer.print("\n", .{});
        return;
    }
    try writer.print(" # {s}\n", .{merged});
}

fn mergeHelpCommentWords(allocator: std.mem.Allocator, description: []const u8) ![]const u8 {
    var out: std.ArrayList(u8) = .empty;
    errdefer out.deinit(allocator);

    var i: usize = 0;
    while (i < description.len) {
        while (i < description.len and helpCommentWhitespace(description[i])) i += 1;
        if (i >= description.len) break;

        if (out.items.len > 0) try out.append(allocator, ' ');
        while (i < description.len and !helpCommentWhitespace(description[i])) : (i += 1) {
            try out.append(allocator, description[i]);
        }
    }

    return out.toOwnedSlice(allocator);
}

fn helpCommentWhitespace(c: u8) bool {
    return c == ' ' or c == '\t' or c == '\n' or c == '\r';
}

fn positionalCompleterAnnotation(path: []const u8, pos: Command.Positional) ![]const u8 {
    if (pos.completion.nu) |completer| return std.fmt.allocPrint(std.heap.page_allocator, "@{s}", .{completer.name});
    if (pos.allowed_values != null and pos.allowed_values.?.len > 0) {
        const name = try positionalCompleterName(path, pos.name);
        defer std.heap.page_allocator.free(name);
        return std.fmt.allocPrint(std.heap.page_allocator, "@{s}", .{name});
    }
    return "";
}

fn flagCompleterAnnotation(path: []const u8, flag_name: []const u8) ![]const u8 {
    const name = try flagCompleterName(path, flag_name);
    defer std.heap.page_allocator.free(name);
    return std.fmt.allocPrint(std.heap.page_allocator, "@{s}", .{name});
}

fn flagCompleterName(path: []const u8, flag_name: []const u8) ![]const u8 {
    return completerName(path, flag_name);
}

fn positionalCompleterName(path: []const u8, positional_name: []const u8) ![]const u8 {
    return completerName(path, positional_name);
}

fn completerName(path: []const u8, value_name: []const u8) ![]const u8 {
    var out: std.ArrayList(u8) = .empty;
    errdefer out.deinit(std.heap.page_allocator);

    try out.appendSlice(std.heap.page_allocator, "complete-");
    try appendIdentifierPart(&out, path);
    try out.append(std.heap.page_allocator, '-');
    try appendIdentifierPart(&out, value_name);

    return out.toOwnedSlice(std.heap.page_allocator);
}

fn appendIdentifierPart(out: *std.ArrayList(u8), text: []const u8) !void {
    var previous_dash = false;
    for (text) |char| {
        const normalized = switch (char) {
            'a'...'z', 'A'...'Z', '0'...'9' => char,
            else => '-',
        };

        if (normalized == '-') {
            if (!previous_dash) try out.append(std.heap.page_allocator, normalized);
            previous_dash = true;
        } else {
            try out.append(std.heap.page_allocator, std.ascii.toLower(normalized));
            previous_dash = false;
        }
    }
}

fn containsValue(values: []const []const u8, needle: []const u8) bool {
    for (values) |value| {
        if (std.mem.eql(u8, value, needle)) return true;
    }
    return false;
}
