# Generated by Fangz for Fangz Forge.
#
# Source this file from Nushell with:
#
#   source fangz.nu
#
# Or place it somewhere stable and source it from your Nushell config.

module completions {

  def complete-project-directory [] {
    ls | get name
  }

  def complete-workspace-setting [] {
    ['output', 'region', 'retries', 'telemetry']
  }

  def complete-fangz-color [] {
    [
      "auto"
      "always"
      "never"
    ]
  }

  def complete-fangz-project-init-template [] {
    [
      "application"
      "library"
      "service"
    ]
  }

  def complete-fangz-project-inspect-output [] {
    [
      "text"
      "json"
      "yaml"
    ]
  }

  def complete-fangz-deploy-strategy [] {
    [
      "rolling"
      "canary"
      "blue_green"
    ]
  }

  def complete-fangz-deploy-region [] {
    [
      "us-east"
      "us-west"
      "eu-central"
      "ap-southeast"
    ]
  }

  def complete-fangz-deploy-variable [] {
    [
      "feature="
      "telemetry="
      "maintenance="
    ]
  }

  def complete-fangz-deploy-environment [] {
    [
      "development"
      "staging"
      "production"
    ]
  }

  def complete-fangz-logs-level [] {
    [
      "trace"
      "debug"
      "info"
      "warn"
      "err"
    ]
  }

  def complete-fangz-logs-service [] {
    [
      "api"
      "worker"
      "web"
    ]
  }

  def complete-fangz-run-task [] {
    [
      "build"
      "test"
      "lint"
      "package"
    ]
  }

  def complete-fangz-config-get-setting [] {
    [
      "output"
      "region"
      "retries"
      "telemetry"
    ]
  }

  def complete-fangz-config-set-setting [] {
    [
      "output"
      "region"
      "retries"
      "telemetry"
    ]
  }

  def complete-fangz-completion-shell [] {
    [
      "bash"
      "zsh"
      "fish"
      "pwsh"
      "nu"
      "nushell"
    ]
  }

  export extern fangz [
    --verbose(-v) # Print detailed progress information. Enable verbose progress messages for every command in the selected command path.
    --color: string@complete-fangz-color # Control terminal color output. Choose automatic color detection, force color, or disable color entirely.
    --config(-c): string # Load configuration from a specific file. Override the default project configuration discovery path.
    --label(-l): string # Attach a repeatable label to the operation. Labels are free-form and are forwarded to project and deployment integrations.
    --define(-D): string # Set a free-form build definition. Each definition must use KEY=VALUE syntax. Definitions are not restricted to a fixed key set.
    --help(-h) # Print help
    --version(-V) # Print version
  ]

  export extern "fangz project" [
    --help(-h) # Print help
  ]

  export extern "fangz project init" [
    --template(-t): string@complete-fangz-project-init-template # Project template to initialize. Templates select the initial module layout and recommended command set.
    --git # Initialize a Git repository. Use --no-git when the project will be placed inside an existing repository.
    --module(-m): string # Add a repeatable starter module.
    --help(-h) # Print help

    directory: string@complete-project-directory # Directory where the project is created.
  ]

  export extern "fangz project inspect" [
    --output(-o): string@complete-fangz-project-inspect-output # Select the inspection output format.
    --resolved # Include inherited and defaulted settings.
    --help(-h) # Print help

    project: string # Project name or path.
  ]

  export extern "fangz project list" [
    --tag(-t): string # Filter by a repeatable project tag.
    --limit: string # Maximum number of projects to return.
    --help(-h) # Print help
  ]

  export extern "fangz deploy" [
    --strategy(-s): string@complete-fangz-deploy-strategy # Rollout strategy. Canary and blue-green deployments introduce additional validation before traffic is switched.
    --parallelism(-p): string # Maximum concurrent deployment workers.
    --timeout: string # Per-artifact timeout in seconds.
    --region(-r): string@complete-fangz-deploy-region # Optional deployment region.
    --wait # Wait for the rollout to become healthy.
    --dry-run # Plan the rollout without applying it.
    --force # Apply despite an existing active rollout.
    --variable(-E): string@complete-fangz-deploy-variable # Set a constrained deployment variable. Variables are validated before the deployment hook executes.
    --help(-h) # Print help

    environment: string@complete-fangz-deploy-environment # Target environment.
    ...artifacts: string # Artifact files to deploy.
  ]

  export extern "fangz publish" [
    --token(-T): string # Publishing credential. A token is required even when publishing to a development registry.
    --signed # Require a signed manifest.
    --help(-h) # Print help

    manifest: string # Release manifest to publish.
  ]

  export extern "fangz logs" [
    --level: string@complete-fangz-logs-level # Minimum log level to return.
    --tail(-n): string # Number of log entries to show.
    --follow(-f) # Continue streaming new log entries.
    --since: string # Only return entries newer than a timestamp.
    --help(-h) # Print help

    service: string@complete-fangz-logs-service # Service whose logs should be queried.
  ]

  export extern "fangz run" [
    --offline # Disable network access for the task.
    --help(-h) # Print help

    task: string@complete-fangz-run-task # Task name to execute.
    ...args: string # Arguments forwarded unchanged to the task.
  ]

  export extern "fangz config" [
    --help(-h) # Print help
  ]

  export extern "fangz config get" [
    --help(-h) # Print help

    setting: string@complete-workspace-setting # Workspace setting name.
  ]

  export extern "fangz config set" [
    --help(-h) # Print help

    setting: string@complete-workspace-setting # Workspace setting name.
    value: string # New setting value.
  ]

  export extern "fangz debug" [
    --dump-tree # Print the registered command tree.
    --help(-h) # Print help
  ]

  export extern "fangz docs" [
    --output-dir(-o): string # Output directory where the AsciiDoc documentation is written.
    --file(-f): string # Output file name.
    --template: string # Optional path to a custom Trama template file (AsciiDoc).
    --help(-h) # Print help
  ]

  export extern "fangz completion" [
    --help(-h) # Print help

    shell: string@complete-fangz-completion-shell # Target shell.
  ]

}

export use completions *
